name: "transformer_bpe_2k"
joeynmt_version: "2.0.0"

data:
    train: "bpe/train2k.BPE.nl-en"  
    dev:   "bpe/dev2k.BPE.nl-en"    
    test:  "bpe/test2k.BPE.nl-en"   
    dataset_type: "plain"
    src:
        lang: "nl"
        level: "bpe"
        lowercase: False
        max_sent_length: 100
        voc_file: "/Users/maritina/Desktop/Uni/MachineTranslation/Exercises/mt-exercise-5/bpe/train2k.BPE.nl"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
            pretokenizer: "none"
            num_merges: 100
            codes: "/Users/maritina/Desktop/Uni/MachineTranslation/Exercises/mt-exercise-5/bpe_codes2k.nl"
    trg: 
        lang: "en"
        level: "bpe"
        lowercase: False
        max_sent_length: 100
        voc_file: "/Users/maritina/Desktop/Uni/MachineTranslation/Exercises/mt-exercise-5/bpe/train2k.BPE.en"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
            pretokenizer: "none"
            num_merges: 100
            codes: "/Users/maritina/Desktop/Uni/MachineTranslation/Exercises/mt-exercise-5/bpe_codes2k.en"
testing:
    beam_size: 5
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    learning_rate: 0.0003
    batch_size: 2048
    batch_type: "token"
    eval_batch_size: 1024
    eval_batch_type: "token"
    scheduling: "plateau"
    patience: 8
    weight_decay: 0.0
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 10
    validation_freq: 500
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "/Users/maritina/Desktop/Uni/MachineTranslation/Exercises/mt-exercise-5/models/bpe2k"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3, 4]
    label_smoothing: 0.3

model:
    initializer: "xavier_uniform"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    tied_embeddings: False  # Set to False for different src and trg languages
    tied_softmax: False
    encoder:
        type: "transformer"
        num_layers: 4
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 512
        dropout: 0
    decoder:
        type: "transformer"
        num_layers: 1
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 512
        dropout: 0
